### ISSUE TITLE
how to calculate PSNR of salient regions

### ISSUE THREAD

**Issue by zjlj** [iamaaditya/image-compression-cnn#15]
hello!,sorry to disturb you !
I download your  code ,but it cant not calculate PSNR of salient regions. which is very import metric.
And this metric demonstrates that this  compression method is indeed able to
preserve visual quality in targeted region.
Would  you please tell me  how to do that ? I would  be grateful to you. It does trouble me a lot.

**Comment by happinessorsorrow** [comment]
I have set a threshould to divide the picture into two parts(ROI and background), then create two pictures:         1)ROI the same as semantic compressed pic, while background region replaced by pixels of the standard JPEG pic
2)background the same as semantic compressed pic,  while ROI region replaced by pixels of the standard JPEG pic
pic1 is compared with the standard JPEG pic to measure the quality of ROI region
pic2 is compared with the standard JPEG pic to mearure the quality of background 
since we pay more attention to ROI region compared with background, we can give a higher weight for the PSNR value of ROI region while measuring the quality of the whole picture.
This does work for me, and I hope it will help you too.

**Comment by happinessorsorrow** [comment]
my email address is: 3292128060@qq.com.

**Comment by zjlj** [comment]
I am very grateful for your patience reply. The experimental method you designed is very good. Thank you for your thoughts. wish you a happy life.
